services:
  mysql:
    image: mysql:8.0
    container_name: mysql_aya_test
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: basedatos
      MYSQL_USER: usuario
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
